### ISSUE TITLE
Why :LeaderfBookmark<CR> always return 'No content!'

### ISSUE THREAD

**Issue by Freed-Wu** [tamago324/LeaderF-bookmark#3]
Thanks!

**Comment by tamago324** [comment]
You need to register a file or directory that you want to bookmark.

Example: To add a bookmark file

1. start with `:LeaderfBookmark!<CR>`.
2. press `N`.
3. enter the file you want to add.
4. enter the name of the bookmark

You should now see it.

Give it a try.

**Comment by Freed-Wu** [comment]
after `:LeaderfBookmark!` i get
```
|| E477: No ! allowed
```

**Comment by tamago324** [comment]
I'm sorry. It was a `:Leaderf! bookmark<CR>`.

**Comment by Freed-Wu** [comment]
after `:Leaderf! bookmark<CR>`

i got
```
|| Error detected while processing function
|| leaderf#Any#start[4]
|| leaderf#LfPy[1]
|| provider#python3#Call[18]
|| Error invoking 'python_execute' on channel 5 (python3-script-host):
|| Traceback (most recent call last):
||   File "<string>", line 1, in <module>
||   File "/home/wzy/.vim/repos/github.com/Yggdroot/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 797, in start
||     the_args.start(arguments, *args, **kwargs)
||   File "/home/wzy/.vim/repos/github.com/Yggdroot/LeaderF/autoload/leaderf/python/leaderf/anyExpl.py", line 729, in _default_action
||     manager.startExplorer(win_pos[2:], *args, **kwargs)
||   File "/home/wzy/.vim/repos/github.com/Yggdroot/LeaderF/autoload/leaderf/python/leaderf/manager.py", line 2005, in startExplorer
||     content = self._getExplorer().getContent(*args, **kwargs)
||   File "/home/wzy/.vim/.cache/init.vim/.dein/autoload/leaderf/python/bookmarkExpl.py", line 24, in getContent
||     return self.getFreshContent()
||   File "/home/wzy/.vim/.cache/init.vim/.dein/autoload/leaderf/python/bookmarkExpl.py", line 27, in getFreshContent
||     bookmark_filepath = lfEval("g:Lf_BookmarkFilePath")
||   File "/home/wzy/.local/lib64/python3.6/site-packages/pynvim/plugin/script_host.py", line 207, in eval
||     obj = self.request("vim_eval", expr)
||   File "/home/wzy/.local/lib64/python3.6/site-packages/pynvim/api/nvim.py", line 182, in request
||     res = self._session.request(name, *args, **kwargs)
||   File "/home/wzy/.local/lib64/python3.6/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
||     raise self.error_wrapper(err)
|| pynvim.api.common.NvimError: Vim:E121: Undefined variable: g:Lf_BookmarkFilePath
```

**Comment by tamago324** [comment]
I'm sorry. I didn't understand the meaning of the question.
Fixed.
May I ask you to confirm this?

**Comment by Freed-Wu** [comment]
it still return error about `g:Lf_BookmarkFilePath`.

I try to set `g:Lf_BookmarkFilePath`. then
```
Leaderf! bookmark
```

it return 'No content!'

OS: gentoo linux 5.4
py: 3.6
vi: nvim 0.4.3

**Comment by tamago324** [comment]
We can't confirm the operation because we don't have Gentoo's environment.
I'm sorry.
